/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.zodo.attendance.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.zodo.attendance.entity.AttendanceDevice.class)
public class AttendanceDevice_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AttendanceDevice,Boolean> active;
    public static volatile SingularAttribute<AttendanceDevice,String> brand;
    public static volatile SingularAttribute<AttendanceDevice,String> deviceType;
    public static volatile SingularAttribute<AttendanceDevice,String> factory;
    public static volatile SingularAttribute<AttendanceDevice,String> host;
    public static volatile SingularAttribute<AttendanceDevice,String> id;
    public static volatile SingularAttribute<AttendanceDevice,String> model;
    public static volatile SingularAttribute<AttendanceDevice,String> name;
    public static volatile SingularAttribute<AttendanceDevice,String> password;
    public static volatile SingularAttribute<AttendanceDevice,String> port;
    public static volatile SingularAttribute<AttendanceDevice,String> sn;
}
