/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.zodo.gateway.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.zodo.gateway.entity.ZodoPassportBlack.class)
public class ZodoPassportBlack_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<ZodoPassportBlack,String> id;
    public static volatile SingularAttribute<ZodoPassportBlack,String> jobId;
    public static volatile SingularAttribute<ZodoPassportBlack,String> reason;
}
