/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.zodo.gateway.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.zodo.gateway.entity.ZodoGatewayLog.class)
public class ZodoGatewayLog_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<ZodoGatewayLog,String> body;
    public static volatile SingularAttribute<ZodoGatewayLog,String> category;
    public static volatile SingularAttribute<ZodoGatewayLog,String> id;
    public static volatile SingularAttribute<ZodoGatewayLog,String> name;
    public static volatile SingularAttribute<ZodoGatewayLog,String> userId;
    public static volatile SingularAttribute<ZodoGatewayLog,String> userName;
}
