/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=entity.ZodoMesLog.class)
public class ZodoMesLog_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<ZodoMesLog,String> body;
    public static volatile SingularAttribute<ZodoMesLog,String> id;
}
